### ISSUE TITLE
Favor positivity in the introduction

### ISSUE THREAD

**Issue by gasche** [bobbypriambodo/ocaml-documentation-guideline#1]
The first sentence of your document is

> The OCaml ecosystem have historically been infamous of having sparse documentations.

and the first few paragraphs mostly talk about some existing documentation is horrible, and then you define your own document as

> The purpose of this guideline is to try to produce a decent standard 

Don't be so negative!

I think you could rephrase the beginning of your document with the goal of saying positive things instead of negative things. It can be as simple as: "This document provides guideline to write good OCaml documentation" -- and it can explain why good documentation is important, but also interesting and rewarding to write.

**Comment by bobbypriam** [comment]
Great points, and yeah we should really be positive. I'll to update it after I finish work later today (or if someone would kindly send a PR before that, it would be great!)

**Comment by dbuenzli** [comment]
Yes please. It's particularly rude to people who have been trying to produce good documentation.

**Comment by bobbypriam** [comment]
That is true, an honest mistake on my part. @dbuenzli would you be able to take a look at the linked PR if it's an acceptable fix? Edit: no pressuring you or Gabriel to review this; I'll probably merge it soon since the current version has a bad connotation.

**Comment by dbuenzli** [comment]
No problem, it's also good if we avoid propagating myths (since depending on the libraries you choose for your development you get good docs...). The fix looks ok however on [this line](https://github.com/bobbypriambodo/ocaml-documentation-guideline/commit/a46365ba4446ccc29780c2aea033fdb86c317a4f#diff-04c6e90faac2675aa89e2176d2eec7d8R40). I wouldn't say "is really important", say that it's a *must*. 

One argument to make for documentation is that in an undocumented system every user loses time understanding the system (lost time is O(n)). In a documented system one person "lost" time documenting the system but it saves time for all the other users (lost time is O(1)).

Also encourage people not to make the documentation as an afterthought but to write it during development. Program design and documentation informs each other, as the latter explains the former and if your explanations are too cumbersome you can assume your design is aswell. That is frame documentation writing as a tool rather than a burden.

**Comment by bobbypriam** [comment]
Thanks! I've updated the PR and incorporated more of your suggestions. I intend to also maintain a list of contributors (and add your names on it), but it'll probably be in a separate PR/commit.
